plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.21'
    id 'org.sinytra.adapter.userdev' version '1.2-SNAPSHOT'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = project.mod_version
group = project.mod_group_id

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Sinytra"
        url = "https://maven.sinytra.org/"
    }
    maven {
        name = "LocalRepo"
        url = uri("repo")
    }
    flatDir {
        dirs 'libs'
    }
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // Connector & FFAPI (via Sinytra Maven)
    additionalRuntimeClasspath "org.sinytra:connector:${project.connector_version}"
    implementation "org.sinytra.forgified-fabric-api:forgified-fabric-api:${project.ffapi_version}"

    // Dependencies
    implementation "maven.modrinth:ldlib:${project.ldlib2_version}"
	implementation "maven.modrinth:sodium:mc1.21.1-0.6.13-neoforge"
	implementation "maven.modrinth:iris:1.8.12+1.21.1-neoforge"
	implementation "maven.modrinth:watermedia:2.1.37"
    implementation "maven.modrinth:bbs-cml-edition:1.10.1-1.21.1"
    implementation "maven.modrinth:photon-editor:mc1.21.1-2.1.3.a-neoforge"
    
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

// Ensure fabric.mod.json and neoforge.mods.toml are included and expanded
processResources {
    inputs.property "version", project.version
    filesMatching(["fabric.mod.json", "META-INF/neoforge.mods.toml"]) {
        expand "version": project.version,
               "file": [jarVersion: project.version]
    }
}
