# NeoForge Properties
neoforge_version=21.1.219
connector_version=2.0.0-beta.12+1.21.1
ffapi_version=0.116.7+2.2.0+1.21.1

# Mod Properties
mod_version=1.1.0
mod_group_id=elgatopro300.bbsphoton
mod_id=bbs_photon_addon

# Dependencies
ldlib2_version=mc1.21.1-2.2.0-neoforge
spruceui_version=6.2.5+1.21.1
lambdynamiclights_version=2.3.2+1.20.1
