modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/Extra/bbs-photon-addon/issues"

[[mods]]
modId="bbs_photon_addon"
version="${file.jarVersion}"
displayName="BBS Photon Addon"
authors="ElGatoPro300"
description='''Integration between BBS and Photon particle engine.'''
logoFile="assets/bbs_photon/icon.png"

[[dependencies.bbs_photon_addon]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.bbs_photon_addon]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.bbs_photon_addon]]
modId="connector"
type="required"
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.bbs_photon_addon]]
modId="bbs"
type="required"
versionRange="[1.9.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.bbs_photon_addon]]
modId="photon"
type="required"
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"
